$foodtruckList = [  {code: 1, foodtruck: "Munchiez"},
                    {code: 2, foodtruck: "Pendong Food Bug"},
                    {code: 3, foodtruck: "Yamashita"},
                    {code: 4, foodtruck: "Road Grille"},
                    {code: 5, foodtruck: "Livelong"},
                    {code: 6, foodtruck: "Cheat Day"},
                    {code: 7, foodtruck: "Binge Beetle"},
                ]

$munchiezMenu = [
                    { code: 1, item: "Australian Porterhouse Steak", price: 205 },
                    { code: 2, item: "Australian Ribeye Steak", price: 160 },
                    { code: 3, item: "Double Ribeye Steak", price: 290 },
                    { code: 4, item: "Ginger Glazed Chicken Wings, 2pcs (with rice)", price: 115 },
                    { code: 5, item: "Ginger Glazed Chicken Wings, 3pcs (with rice)", price: 135 },
                    { code: 6, item: "6pcs Ginger Glazed Chicken Wings (Regular)", price: 175 },
                    { code: 7, item: "6pcs Ginger Glazed Chicken Wings (Spicy)", price: 185 },
                ]

$pendongMenu =  [
                    { code: 1, item: "Chicken Kebab", price: 145 },
                    { code: 2, item: "Chicken Kebab (with rice)", price: 160 },
                    { code: 3, item: "Chicken Kebab (with rice and drinks)", price: 175 },
                    { code: 4, item: "Pork BBQ Platter (10 sticks)", price: 165 },
                    { code: 5, item: "Marinated Grilled Porkchop", price: 190 },
                    { code: 6, item: "Marinated Grilled Porkchop (with drinks)", price: 205 },
                    { code: 7, item: "Grilled Pork Steak", price: 185 },
                    { code: 8, item: "Pork BBQ Meal", price: 105 },
                    { code: 9, item: "Pork BBQ Meal (with drinks)", price: 120 },
                    { code: 10, item: "Grilled Pink Salmon", price: 115 },
                    { code: 11, item: "Grilled Pink Salmon (with drinks)", price: 130 },
                    { code: 12, item: "Pendong Lemonade Fizz (Green Apple, Passion Fruit, Watermelon)", price: 60 },
                ]

$yamashitaMenu = [
                    { code: 1, item: "Ramen (Soy sauced based)", price: 120},
                    { code: 2, item: "Miso Ramon", price: 140},
                    { code: 3, item: "Shio Ramen (Salt based)", price: 130},
                    { code: 4, item: "Pork ramen", price: 160},
                    { code: 5, item: "Spicy Ramen", price: 140},
                    { code: 6, item: "Wakame Ramen", price: 130},
                    { code: 7, item: "Miso corn butter", price: 200},
                    { code: 8, item: "Cantonese Ramen", price: 200},
                    { code: 9, item: "Yakisoba (Japanese style fried noodle)", price: 170},
                    { code: 10, item: "Cold Ramen ('Hiyashi Chuka')", price: 190},
                    { code: 11, item: "Chicken Curry", price: 160},
                    { code: 12, item: "Karaage Curry (Fried chicken)", price: 180},
                    { code: 13, item: "Shrimp Fried Curry", price: 180},
                    { code: 14, item: "Oyako don (Chicken wrapped with egg)", price: 150},
                    { code: 15, item: "Tanin don (Pork wrapped with egg)", price: 150},
                    { code: 15, item: "Karaage don (Fried chicken)", price: 150},
                    { code: 15, item: "Yakiniku don (Fried beef with special sauce)", price: 190},
                    { code: 15, item: "Shogayaki don (Ginger pork)", price: 190},
                    { code: 15, item: "Katsu don (Breaded pork with egg)", price: 210},
                    { code: 15, item: "Pork rice topping", price: 90},
                    { code: 15, item: "Spicy pork rice topping", price: 110},
                    { code: 15, item: "Chahan (Japanese fried rice)", price: 160},
                    { code: 15, item: "California mango rolls", price: 160},
                    { code: 15, item: "Salad maki", price: 150},
                    { code: 15, item: "Karaage rolls (Fried chicken)", price: 140},
                    { code: 15, item: "Onion salmon rolls", price: 170},
                    { code: 15, item: "Tekka maki (Tuna)", price: 150},
                    { code: 15, item: "Salmon maki", price: 150},
                    { code: 15, item: "Gyoza (Japanese dumpling 6 pcs)", price: 90},
                    { code: 15, item: "Karaage (Fried chicken 3 pcs)", price: 90},
                    { code: 15, item: "Shrimp Fries (with special sauce 4 pcs)", price: 140},
                    { code: 15, item: "Plain Japanese rice", price: 50},
                  ]

$roadgrilleMenu = [
                  { code: 1, item: "Grilled Pork Ribs", price: 185},
                  { code: 2, item: "Grilled Quarter Chicken", price: 105},
                  { code: 3, item: "Grilled Hungarian Sausage", price: 115},
                  { code: 4, item: "SquadGoal Bundle (good for 4-6 persons)", price: 985},
                  { code: 5, item: "Chicken Wings", price: 175},
                  { code: 6, item: "Poutine", price: 115},
                  { code: 7, item: "Fries", price: 65},
                  { code: 8, item: "Grilled Corn", price: 55},
                  { code: 9, item: "Coleslaw", price: 45},
                  { code: 10, item: "Rice", price: 20},
                  { code: 11, item: "Deep Fried Ice Cream", price: 125},
                  { code: 12, item: "Mineshine Milk Tea", price: 55},
                  { code: 13, item: "Sola Iced Tea", price: 50},
                  { code: 14, item: "Mon Passion RTD Coffee", price: 55},
                  { code: 16, item: "Pineapple Juice", price: 40},
                  { code: 17, item: "Soda Cans", price: 35},
                  { code: 18, item: "Bottled water", price: 20},
                  { code: 19, item: "Brewed Coffee", price: 30},
                  { code: 20, item: "Italian SODA", price: 65},
                  { code: 21, item: "Regular sized Square Burger", price: 225},
                  { code: 22, item: "Giant Square Burger", price: 375},
                  { code: 23, item: "Giant Hotdog Sandwich w/ Fries (single)", price: 135},
                  { code: 24, item: "Sausage Sandwich w/ Fries (single)", price: 135},
                  ]

$livelongMenu = [
                  { code: 1, item: "Detox Smoothies (11 Different Flavors Available)", price: 120},
                  { code: 2, item: "Fruit Shakes (4 Different Flavors Available)", price: 60},
                  { code: 3, item: "Lemonade (3 Different Flavors Available)", price: 90},
                  { code: 4, item: "Matcha Shake", price: 100},
                  ]

$cheatdayMenu =  [
                   { code: 1, item: "[BESTSELLER] Giant Taco", price: 165},
                   { code: 2, item: "[BESTSELLER] Quesadilla Tower", price: 195},
                   { code: 3, item: "[BESTSELLER] Pizza Quesadilla", price: 195},
                   { code: 4, item: "[BESTSELLER] Sisig Burrito", price: 185},
                   { code: 5, item: "Bagnet with Mexican Rice", price: 165},
                   { code: 6, item: "Dinakdakan Bagnet", price: 90},
                   { code: 7, item: "Chicken Mole", price: 145},
                   { code: 8, item: "Sopa de Bagnet", price: 140},
                   { code: 9, item: "Churros with Handmade Creamery", price: 120},
                   { code: 10, item: "Halohalo Quesadilla", price: 120},
                   { code: 11, item: "Cream Cheese with Yema Quesadilla", price: 120},
                 ]

$bingebeetleMenu = [
                   { code: 1, item: "Pasta Pomodoro", price: 129},
                   { code: 2, item: "Honey Mustard Chicken", price: 129},
                   { code: 3, item: "Cheesy Chicken", price: 129},
                   { code: 4, item: "Sloppy Joes", price: 129},
                   { code: 5, item: "German Franks Cheesy Franks", price: 99},
                   { code: 6, item: "Lechon Kawali", price: 99},
                   { code: 7, item: "Popcorn Chicken", price: 85},
                   { code: 8, item: "Turon a la Mode", price: 65},
                   { code: 9, item: "Bacon ice cream [Single Scoop]", price: 55},
                   { code: 10, item: "Bacon ice cream [Double Scoop]", price: 75},
                   { code: 11, item: "Ice Cream Cookie Cups", price: 65},
                   { code: 12, item: "Cheesecake Springrolls", price: 90},
                   ]
